# Introduction to Python

---
## 1. Things to Know Before We Get Started:
* We will be using Spyder to run scripts and develop projects. Spyder is an integrated development environment (IDE), comparable to MATLAB, used to develop programs. 
* Comment lines of code with `#`.
* Create sections with `# %%` in Spyder.
* Stop script execution in Spyder Select "Projects" --> Select "Restart kernel" or `Ctrl+.`.
* Why Python?? It's Open source, capable, and FREE!!
* __BEWARE__: For those familiar with C based languages and other languages that use an explicit implementation of pointers, Python automatically creates pointers to variables set equal to one another. Further discussion of how pointers work in Python can be found here https://realpython.com/pointers-in-python/.
* Reference PEP 8 for style help https://www.python.org/dev/peps/pep-0008/.



---
## 2. Basic Math: Arithmetic Operators
* Reference material https://www.w3schools.com/python/python_operators.asp

### 2.1 Addition Operator, `+`
* Add values together

In [ ]:
3 + 5

### 2.2 Subtraction Operator, `-`
* Subtract one value from another

In [ ]:
2 - 8

### 2.3 Multiplication Operator, `*`
* Multiply values together

In [ ]:
3 * 6

### 2.4 Division Operator, `/`
* Divide one value by another

In [ ]:
12 / 5

### 2.5 Exponentiation Operator, `**`
* Raise a value to a power

In [ ]:
4 ** 2

### 2.6 Floor Division Operator, `//`
* Returns a value rounded down to the nearest whole number of one value divided by another

In [ ]:
12 // 5

___
## 3. Comparison Operators and Logical Operators
* Reference material https://www.w3schools.com/python/python_operators.asp

### 3.1 Greater than, `>`

In [ ]:
2 > 1

### 3.2 Less than, `<`

In [ ]:
2 < 1

### 3.3 Greater than or Equal to, `>=`

In [ ]:
2 >= 2

### 3.4 Less Than or equal to, `<=`

In [ ]:
2 <= 1

### 3.5 Equal TO, `==`

In [ ]:
2 == 1

### 3.6 Not Equal TO, `!=`

In [ ]:
2 != 1

### 3.7 Logical Operator: `and`

In [ ]:
(2 > 3) and (3 > 2)

### 3.8 Logical Operator: `or`

In [ ]:
(2 > 3) or (3 > 2)

---
## 4. Lists:
* Lists can store lists `list`, integers `int`, floating point `float`, strings `str`, tuples `tuple`, Booleans `bool`, and other data types. We will focus primarily on lists, integers, and floating points.
* Lists are sequential (ordered) and can be both indexed and sliced. 
* The first element (item) of a list in Python like many languages including Java, C, C##, is `0`. This differs from MATLAB which uses `1` as the first element in a list.
* Reference material https://www.w3schools.com/python/python_lists.asp


### 4.1 Creating a List
* Lists are denoted with square brackets `[]` with elements being separated using commas `,`. 
* If a `list` is desired, avoid using parentheses `()` to ensure Python does not create a `tuple`.

In [ ]:
[1, 2, 3, 4] 

### 4.2 Assigning a List to a Variable
* Lists and other data types can be assigned to a variable using the operator `=`.
* Reserved words such as `list` and `int` should not be used as variables. Reserved words can be identified in Spyder and Jupytor Notebooks by a change in coloration. 
* Variable names should be lowercase and words should be separated with underscores. Focus on using descriptive variable names. Examples: `var`, `var_example`, `more_var_examples`.

In [ ]:
my_list = [1, 2, 3, 4] 
print(my_list)

### 4.3 Indexing and Slicing Lists
* Specific elements can be retrieved by using the list name followed by the desired index value in square brackets. Using a negative index value indexes from the end of the list to the beginning. Notation: `variable_name[index_value]` 
* Slicing can be performed to grab more than one element. Notation: `variable_name[start : stop]` with start being the first index value and stop being the last value which is not included.


In [ ]:
my_list[0]   #grab specific element

In [ ]:
my_list[2]   

In [ ]:
my_list[-1]  #using a negative index value indexes from the end of the list to the beginning

In [ ]:
my_list[1:3] #grab specific elements

In [ ]:
my_list[::]  #using two colens grabs an entire list

---
## 5. Lists of Lists:
* Lists can store lists creating lists of lists or multidimensional arrays.
* Reference material https://www.w3schools.com/python/python_lists.asp


### 5.1 Creating a List of Lists

In [ ]:
my_list_of_lists = [my_list,[11,23,33,44],my_list]
print(my_list_of_lists)

### 5.2 Indexing and Slicing Lists of Lists

In [ ]:
my_list_of_lists[1]      #grab a list from list of lists

In [ ]:
my_list_of_lists[2][::]  #grab a list from list of lists

In [ ]:
my_list_of_lists[1][3]   #grab an element from a list in list of lists

In [ ]:
my_list_of_lists[0:2]    #slice lists from list of lists

In [ ]:
my_list_of_lists[2][0:4] #slice elements from a list in list of lists

---
## 6. NumPy Arrays:
* NumPy is a Python library that enables the use of multidirectional arrays and other high level mathematical functions. 
* Libraries must be imported to be used. Notation: `import` library_name
* Libraries can be imported with a shorter name than the library name to reduce typing and for clarity. Notation: `import` library_name `as` short_name
* Reference material https://www.w3schools.com/python/numpy/numpy_intro.asp

In [3]:
import numpy as np # numpy is conventionally imported as np

### 6.1 Creating NumPy Arrays

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
my_array = np.array([1,2,3,4]) # 1D array
print(my_array)

[1 2 3 4]


In [6]:
my_multi_array = np.array([my_array,[11,23,33,44],my_array]) #2D array
print(my_multi_array)

[[ 1  2  3  4]
 [11 23 33 44]
 [ 1  2  3  4]]


### 6.2 Performing Mathematical Operations on Matrices

In [7]:
my_multi_array + 3 # add a value to every element

array([[ 4,  5,  6,  7],
       [14, 26, 36, 47],
       [ 4,  5,  6,  7]])

In [8]:
my_multi_array - 3 # subtract a value from every element

array([[-2, -1,  0,  1],
       [ 8, 20, 30, 41],
       [-2, -1,  0,  1]])

In [ ]:
my_multi_array * 3 # multiply every element by a value

In [9]:
my_multi_array / 3 # divide every element by a value

array([[ 0.33333333,  0.66666667,  1.        ,  1.33333333],
       [ 3.66666667,  7.66666667, 11.        , 14.66666667],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333]])

In [10]:
my_matrix = np.array([[3,2],[9,7]]) #Create new array
print(my_matrix)
print('\n')
my_matrix.transpose() # transpose array with the format: np_array.transpose()

[[3 2]
 [9 7]]




array([[3, 9],
       [2, 7]])

In [11]:
my_new_matrix = np.array([[1,3],[4,6]]) #Create new array
print(my_new_matrix)
print('\n')
np.linalg.inv(my_new_matrix) #Find inverse of array with the format: np.linalg.inv(np_array, np_array)


[[1 3]
 [4 6]]




array([[-1.        ,  0.5       ],
       [ 0.66666667, -0.16666667]])

In [12]:
np.dot(my_matrix, my_new_matrix) # Find the dot product with the format: np.dot(np_array, np_array)

array([[11, 21],
       [37, 69]])

In [13]:
np.cross(my_matrix, my_new_matrix) # Find the cross product with the format: np.cross(np_array, np_array)

array([ 7, 26])

---
## 7. Pandas:
* Pandas like NumPy is a library that adds additional capabilities.
* Pandas is great for importing csv files and organizing data with pandas data frames
* Reference material https://www.w3schools.com/python/pandas/pandas_intro.asp


In [ ]:
import pandas as pd # pandas is conventionally imported as pd

### 7.1 Importing a CSV File
* Set a variable equal to the CSV that is read in and stored as a pandas data frame
* To import a CSV file use the format: `pd.read_csv('file_name.csv')`
* If the file is not in the same folder as the script being used to import the csv include the file extension.
* Pandas data frames create a column that serves as the index


In [ ]:
data = pd.read_csv('example.csv')# import CSV file of example data acquisition system (DAS) data from a C_12 and assign it to variable 'data'
print(data)

### 7.2 Assigning Column of Data to Variable
* Data from specific columns can be grabbed and assigned to variables.
* The data is grabbed using the heading. Format: `specific_data = data_frame_name.heading_of_column`

In [ ]:
data_from_list_one = data.GPS_SPD # assigns GPS_SPD to variable
print(data_from_list_one)

### 7.3 Casting Pandas Dataframe to a List.
* Depending on your needs it may be necessary to convert the pandas data frame to a list. This is done using casting.
* Casting assigns a datatype to specific sets of data/variables allowing for data type specific functions to be performed. Notation: `new_data_type(data_in_old_data_type)`

In [ ]:
data_from_list_one = list(data_from_list_one) #turns the pandas data frame column into a list.
print(data_from_list_one)

### 7.4 Export Pandas Dataframe to CSV File
* To export to a CSV file use the format: `pd.to_csv('file_name.csv')`

In [ ]:
data.to_csv('example_csv.csv', index=False) #Setting the index to 'False' does not export the index column to the csv file

---
## 8. Control Flow Statements:
* Python has `for` statements, `while` statements, and `if` statements
* Python uses indentations to mark blocks of code unlike other languages like C which use curly brackets.
* Reference material `for` loops https://www.w3schools.com/python/python_for_loops.asp
* Reference material `while` loops https://www.w3schools.com/python/python_while_loops.asp
* Reference material `if` statements https://www.w3schools.com/python/python_conditions.asp

### 8.1 `for` Statements
* `for` loops execute code in the loop a specified number of times. Notation: `for item_in_list in my_list1:`

In [ ]:
my_list1 = np.linspace(0, 30 , 6) #linspace is a NumPy function that can be used to create lists. 
#Notation: np.linspace(start, end, total_elements) with start begin the first value end being 
#the last value and total_elements the number of equally spaced elements to be created
print(my_list1)

In [ ]:
for items in my_list1:
    print(items)

In [ ]:
my_list2 = range(0, 10, 1) #range is a built in function that can be used to create a sequece of numbers.
#Notation: range(start, stop, step) start is the first number of the sequence, stop is the number
#the sequence stops at and is not included in the sequence, and step is the 
for items in my_list2:
    print(items)

### 8.2 `while` Statements
* `while` loops execute code until a condition is not met. Notation `while items_in_list logicstatement value:`

In [ ]:
i = 0 #create counter for indexing purposes
while my_list1[i] < 20: #while element in my_list is less than 20 execute loop
    print(my_list1[i]) #print my_list1 value that is below 20
    i += 1 #count i up by one every time through loop

### 8.3 `if`, `elif`, `else` Statements
* `if` statements execute the block of code they contain if the `if` statement is true. Notation `if value logicstatement value:`
* `elif` statements are used if multiple conditions need to be checked and work the same as `if` statements Notation `elif value logicstatement value:`
* `else` statements execute if previous conditions are not met. Notation `else:`


In [ ]:
if 2 > 1: 
    print('Hello')

In [ ]:
if 1 > 1: 
    print('Hello')
elif 2 > 1:
    print('Hello 2')

In [ ]:
if 1 > 1: 
    print('Hello')
elif 2 < 1:
    print('Hello 2')
else:
    print('none')

---
## 9. Functions:
* Functions are great for repetition so that segments of code does not need to be repeated.
* There are 2 main parts when using functions the function call and the function definition: Notation: function defintition `def my_function(variable(s)_to_pass_into_Function):` function call `varaible_for_returned_value = my_function(variable(s)_to_pass_into_Function)`
* Reference material https://www.w3schools.com/python/python_functions.asp

In [ ]:
def greater_than_7(list_value): #define the function
    if list_value > 7:       #test the value sent into function and see what the result is
        return('Yes')
    else:
        return('No')

list_value = 5
result = greater_than_7(list_value) #use function to test value
print(result)

In [ ]:
def greater_than_7(list_value):
    if list_value > 7:
        return('Yes')
    else:
        return('No')

for x in my_list1:
    result = greater_than_7(x)
    print(result)

---
## Exercises:

### 4. Lists

4.1 Create a list with the numbers `12, 23, 24, 56, 67, 23` and assign it to a variable named `my_first_list`. Print `my_first_list`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol1" class='btn btn-primary'>Solution</button>
<div id="sol1" class="collapse">
   
```python
my_first_list = [12, 23, 24, 56, 67, 23]
print(my_first_list)
```

4.2 Return the value `56` from `my_first_list` using 2 methods

In [ ]:
# Insert your first method here

In [ ]:
# Insert your second method here

<button data-toggle="collapse" data-target="#sol2" class='btn btn-primary'>Solution</button>
<div id="sol2" class="collapse">
   
```python
# first method
my_first_list[3]
# second method
my_first_list[-3]
```

4.3 Return the `24, 56, 67` from `my_first_list` using slicing

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol3" class='btn btn-primary'>Solution</button>
<div id="sol3" class="collapse">
   
```python
my_first_list[2:5]
```

### 5. Lists of Lists

5.1 Create a list called `my_first_list_of_lists` composed of 3 elements. Make each element `my_first_list`. Print `my_first_list_of_lists`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol4" class='btn btn-primary'>Solution</button>
<div id="sol4" class="collapse">
   
```python
my_first_list_of_lists = [my_first_list,my_first_list,my_first_list]
print(my_first_list_of_lists)
```

5.2 Select `12` from the third list in `my_first_list_of_lists`

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol5" class='btn btn-primary'>Solution</button>
<div id="sol5" class="collapse">
   
```python
my_first_list_of_lists[2][0]
```

### 6. NumPy Arrays:

6.1 Create a 1D NumPy array with the numbers `12, 25, 45, 35, 45, 45` with the name `my_numpy_array_1D`. Print `my_numpy_array_1D`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol6" class='btn btn-primary'>Solution</button>
<div id="sol6" class="collapse">
   
```python
my_numpy_array_1D = np.array([12, 25, 45, 35, 45, 45])
print(my_numpy_array_1D)
```

6.2 Create a 2D NumPy array named `my_numpy_array_2D` with 3 rows. Set each row equal to `my_numpy_array_1D`

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol7" class='btn btn-primary'>Solution</button>
<div id="sol7" class="collapse">
   
```python
my_numpy_array_2D = np.array([my_numpy_array_1D,my_numpy_array_1D,my_numpy_array_1D])
print(my_numpy_array_2D)
```

6.3 Multiply every element in `my_numpy_array_2D` by `3`

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol8" class='btn btn-primary'>Solution</button>
<div id="sol8" class="collapse">
   
```python
my_numpy_array_2D * 3
```

6.4 Find the transpose of `my_numpy_array_2D`

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol9" class='btn btn-primary'>Solution</button>
<div id="sol9" class="collapse">
   
```python
my_numpy_array_2D.transpose()
```

### 7. Pandas:

7.1 Import the CSV file named `example.csv` and assign it to a variable named `data1`. Print `data1`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol10" class='btn btn-primary'>Solution</button>
<div id="sol10" class="collapse">
   
```python
data1 = pd.read_csv('example.csv')
print(data1)
```

7.2 Create a variable named `gps_lat` and assign the column `GPS_P_LAT2` to it. Print `gps_lat`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol11" class='btn btn-primary'>Solution</button>
<div id="sol11" class="collapse">
   
```python
gps_lat = data1.GPS_P_LAT2
print(gps_lat)
```

### 8. Control Flow Statements:

7.1 Create a list named `my_numbers` containing '23, 45, 56, 73, 96'. Use a `for` loop to print every element in the list. In the `for` loop call the `item_in_list` from section 7 `x`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol12" class='btn btn-primary'>Solution</button>
<div id="sol12" class="collapse">
   
```python
my_numbers = [23, 45, 56, 73, 96]
for x in my_numbers:
    print(x)
```

8.2 Create a `while` loop that prints all the numbers in `my_numbers` less than `60`. Create a counter named `j`.

In [ ]:
# Insert your solution herej = 0

<button data-toggle="collapse" data-target="#sol13" class='btn btn-primary'>Solution</button>
<div id="sol13" class="collapse">
   
```python
j = 0
while my_numbers[j] < 60:
    print(my_numbers[j])
    j += 1
```

8.3 Create an `if` statement that prints TRUE if `3` is greater than `2`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol14" class='btn btn-primary'>Solution</button>
<div id="sol14" class="collapse">
   
```python
if 3 > 2:
    print('TRUE')
```

### 9. Functions:

9.1 Create a function named `my_first_func` that takes in an argument named `number` and returns `Yes` if it is greater than 50 and `No` if it is less than 50.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol15" class='btn btn-primary'>Solution</button>
<div id="sol15" class="collapse">
   
```python
def my_first_func(number):
    if number > 50:
        return ('Yes')
    else:
        return ('No')
```

9.2 Create a `for` loop that passes the elements of `my_numbers` into `my_first_func`, setting what the function returns equal to `answer`. Print `answer`. In the `for` loop call the `item_in_list` from section 7 `x`.

In [ ]:
# Insert your solution here

<button data-toggle="collapse" data-target="#sol16" class='btn btn-primary'>Solution</button>
<div id="sol16" class="collapse">
   
```python
for x in my_numbers:
    answer = my_first_func(x)
    print (answer)
```